# Generated by Django 2.1.4 on 2018-12-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField()),
                ('date_completed', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
